PRAGMA foreign_keys = ON;

CREATE TABLE posts(
    postid INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    title VARCHAR(40) NOT NULL,
    text VARCHAR(4096) NOT NULL,
    created DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE art(
    artid INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    filename VARCHAR(64) NOT NULL,
    title VARCHAR(40) NOT NULL,
    text VARCHAR(4096) NOT NULL, 
    created DATETIME DEFAULT CURRENT_TIMESTAMP
);